name: build-push

on:
  push:
    branches: [master]

jobs:

  CI_CD:
    name: get version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: version
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    
    - name: show-version
      run: echo "Version to build -> ${{ steps.version.outputs.sha_short }}"

    - name: build-and-push
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: brianwolf94/sensorial-raspberry
        tags: ${{ steps.version.outputs.sha_short }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        registry: docker.io
        buildArgs: 
        - ARG_VERSION: ${{ steps.version.outputs.sha_short }}
    
    - name: tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        CUSTOM_TAG: ${{ steps.version.outputs.sha_short }}
    
    outputs:
      sha_short: ${{ steps.version.outputs.sha_short }}