name: cicd

on:
  push:
    branches: [master]

jobs:

  get-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create-version
      id: create-version
      run: echo "::set-output name=version::$(date +%Y%m%d%H%M)"
    - name: show-version
      run: echo "Version to build -> ${{ steps.create-version.outputs.version }}"
    outputs:
      version: ${{ steps.create-version.outputs.version }}
  
  build-and-push:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build-and-push
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: brianwolf94/sensorial-raspberry
        tags: ${{ needs.get-version.outputs.version }}, latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        registry: docker.io
        buildArgs: ARG_VERSION=${{ needs.get-version.outputs.version }}
    outputs:
      version: ${{ needs.get-version.outputs.version }}
  
  tag-branch:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: tag
      id: tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.build-and-push.outputs.version }}